name: Veracode SAST and SCA Scan

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch:
  
jobs:
  remove-veracode-profile:
    runs-on: ubuntu-latest
    name: Remove Verademo Java Maven
    container:
      image: veracode/api-signing:latest
    steps:
      - name: remove Veracode Profile
        run: |
          export VERACODE_API_KEY_ID=${{ secrets.VERACODE_API_ID }}
          export VERACODE_API_KEY_SECRET=${{ secrets.VERACODE_API_KEY }}
          guid=$(http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v1/applications?name=verademo-java-maven" | jq -r '._embedded.applications[] | select(.profile.name == "verademo-java-maven") | .guid')
          echo GUID: ${guid}
          http --auth-type=veracode_hmac DELETE "https://api.veracode.com/appsec/v1/applications/${guid}"



